### ISSUE TITLE
URL Encode filenames

### ISSUE THREAD

**Issue by PatrickRose** [thephpleague/flysystem-rackspace#12]
It's mentioned briefly in the docs for OpenCloud that file names should be URL encoded if they're non-standard. Should the Rackspace adapter be handling this, or should I ensure my filenames are URLEncoded before passing them down the chain?

**Comment by frankdejonge** [comment]
@PatrickRose this should probably be handled within the adapter.

**Comment by frankdejonge** [comment]
@PatrickRose which kind of url encoding do they require here? urlencode or rawurlencode? Do you have the link to the docs?

**Comment by PatrickRose** [comment]
I'm using `rawurlencode` (though I can't remember why offhand) [Docs have a notice here](http://docs.php-opencloud.com/en/latest/services/object-store/objects.html#create-an-object)

**Comment by frankdejonge** [comment]
@PatrickRose the docs say we should be using `urlencode`, I'll use that for all the segments, commit incoming.

**Comment by PatrickRose** [comment]
Ahh, I remember why. Guzzle under the hood replaces `' '` with `'%20'`. We spotted this after we'd been using it for a while so we needed to keep the filenames the same. Would it be possible to use `rawurlencode`?

**Comment by frankdejonge** [comment]
@PatrickRose does it matter that it does it? because urlencode replaces it with `+` so Guzzle can't replace it anymore.

**Comment by PatrickRose** [comment]
It's a definite BC break, because previously `$filesystem->exists('some file')` would return true, and with `urlencode` it wouldn't.

**Comment by frankdejonge** [comment]
ah, so it actually SHOULD be rawurlencode.

**Comment by frankdejonge** [comment]
Corrected that.

**Comment by PatrickRose** [comment]
I think there's a minor BC break as part of this, so not sure how you want to handle it (I believe it's cases like `$filesystem->put('some#file')` actually wrote to `'some'`)

**Comment by frankdejonge** [comment]
@PatrickRose ~_^

**Comment by PatrickRose** [comment]
Sorry <3

I _think_ it's okay - it's rare that people have those in their file names, which was something I had to deal with because users.

**Comment by frankdejonge** [comment]
:neckbeard:
