### ISSUE TITLE
Instance of Closure given

### ISSUE THREAD

**Issue by AlexandreHagen** [thephpleague/flysystem-rackspace#16]
Hi, since the last release I got this: 

```
Type error: Argument 1 passed to LeagueFlysystemRackspaceRackspaceAdapter_XXXXX::__construct() must be an instance of OpenCloud\ObjectStore\Resource\Container, instance of Closure given, called in /var/www/demophonie/app/cache/dev/appDevDebugProjectContainer.php on line 6614
```

I tried alone to debug it but without results. 
Have you any idea ? 

I'm under Symfomy 2.8.2 and PHP7.0.2. From my point of view, issue is linked to dependency injection.

Thanks.

**Comment by frankdejonge** [comment]
@AlexandreHagen are you using the 1up bundle?

**Comment by frankdejonge** [comment]
Also, I think your assessment is correct. It looks like a service definition problem.

**Comment by AlexandreHagen** [comment]
Yes I use `1up-lab/OneupFlysystemBundle`. But I don't use `1up-lab/OneupUploaderBundle`

Here what I'm using to file upload: 

```
"oneup/flysystem-bundle": "1.3.0",
"league/flysystem-cached-adapter": "1.0.3",
"league/flysystem-rackspace": "1.0.4",
"vich/uploader-bundle": "0.14.0",
```

**Comment by frankdejonge** [comment]
@AlexandreHagen did you file an issue with the @1up-lab people? If so, was it resolved there? /cc @bytehead

**Comment by bytehead** [comment]
@AlexandreHagen how does your configuration look like? 
There are some other guys working with Rackspace (1up-lab/OneupFlysystemBundle#86), maybe this helps. Otherwise open a ticket at [1up-lab/OneupFlysystemBundle](https://github.com/1up-lab/OneupFlysystemBundle/issues).

**Comment by AlexandreHagen** [comment]
Problems solve! It was configuration issues in 1up-lab/OneupFlysystemBundle. I pass all `lazy: true` to `lazy: false` in configuration file (config.yml). Thanks for your help!

**Comment by frankdejonge** [comment]
@bytehead ^ the previous comment might be interesting for you to dig into :)
@AlexandreHagen thanks for coming back and closing the issue!
