### ISSUE TITLE
Get object URL

### ISSUE THREAD

**Issue by modmanx** [thephpleague/flysystem-rackspace#2]
I tried to get a URL of a object, and I did not find any other way then making "getObject" method public and then call "$disk->getDriver()->getAdapter()->getObject('uploads/file.txt')->getUrl()"
Is there any other way, or implementing "getObjectUrl" method would be a good solution?

**Comment by ShortlyMAB** [comment]
+1

**Comment by harikt** [comment]
What I did was something like `$container->getCdn()->getCdnUri() . '/' . $filename;` . I am also interested to know alternatives.

**Comment by frankdejonge** [comment]
The way to solve this would to add a plugin to this repository which is rackspace only. Since this is not something other adapters provide it can't be in the main Filesystem interface.

**Comment by frankdejonge** [comment]
The container accessor has been added, resolving this issue as described above.
