### ISSUE TITLE
PHP Warning:  fclose(): xx is not a valid stream resource

### ISSUE THREAD

**Issue by harikt** [thephpleague/flysystem-rackspace#7]
I was making use of the Rackspace adapter via flysytsem .

The code is as below .

``` php
$flysystem = new Filesystem(new RackspaceAdapter($container));
$fp = fopen($file, 'r+');
if ($fp) {
    $flysystem->writeStream($destination, $fp);
    fclose($fp);
}
```

I noticed when trying to close it says not a resource.

PHP Warning:  fclose(): xx is not a valid stream resource in ...

Wonder whether flysystem at some point is automatically closing the same ?

Good thing is it is sending the data to the Cloud. So the file is already present on both local and server :) .

**Comment by frankdejonge** [comment]
@harikt Hi, this is something I know. The rackspace sdk closes the resource internally. Which is a unexpected side-effect. One should always first check if the resource is still valid before closing.

**Comment by harikt** [comment]
Thank you. Just wanted to mention it.

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by dopesong** [comment]
If I'm correct Amazon S3 SDK does the same.

So I think there should be mentioned that about it:

```
if (is_resource($stream)) {
    fclose($stream);
}
```

**Comment by harikt** [comment]
I do agree it will be nice to mention it.
